# Generated by Django 4.1.7 on 2023-03-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emailuser_next_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
