# Generated by Django 4.1.7 on 2023-03-20 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'branch',
                'verbose_name_plural': 'branches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'family',
                'verbose_name_plural': 'families',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='encyclopedia.family', verbose_name='family')),
            ],
            options={
                'verbose_name': 'genus',
                'verbose_name_plural': 'genuses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlantClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('branch', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.CASCADE, to='encyclopedia.branch', verbose_name='branch')),
            ],
            options={
                'verbose_name': 'class',
                'verbose_name_plural': 'classes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='scientific name')),
                ('source_id', models.CharField(max_length=15, verbose_name='source id')),
                ('source_reference', models.CharField(blank=True,
                 max_length=255, null=True, verbose_name='source reference')),
                ('genus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='encyclopedia.genus', verbose_name='genus')),
            ],
            options={
                'verbose_name': 'specie',
                'verbose_name_plural': 'species',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlantOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('plant_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='encyclopedia.plantclass', verbose_name='class')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='family',
            name='plant_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='encyclopedia.plantorder', verbose_name='order'),
        ),
    ]
